/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_yxkj_jnidemo_MyJniDemo */

#ifndef _Included_com_yxkj_jnidemo_MyJniDemo
#define _Included_com_yxkj_jnidemo_MyJniDemo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_yxkj_jnidemo_MyJniDemo
 * Method:    getString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_yxkj_jnidemo_MyJniDemo_getString
  (JNIEnv *, jclass);

/*
 * Class:     com_yxkj_jnidemo_MyJniDemo
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_yxkj_jnidemo_MyJniDemo_add
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
